### ISSUE TITLE
Add @jmooring to ACKNOWLEDGEMENTS unless he would rather not be there

### ISSUE THREAD

**Issue by danielfdickinson** [danielfdickinson/build-audit-action-hugo-dfd#34]
@jmooring Any objection to my adding a thanks for your Hugo forum audit code in https://github.com/danielfdickinson/build-audit-action-hugo-dfd/blob/main/docs/ACKNOWLEDGEMENTS.md ?
I'm trying to make sure I give credit where credit is due, and I don't think this would look like you were responsible for any breakage I might have.

**Comment by jmooring** [comment]
I have no objection.
