### ISSUE TITLE
Make sure I haven't unconfirmed ACKNOWLEDGMENTS

### ISSUE THREAD

**Issue by danielfdickinson** [danielfdickinson/build-audit-action-hugo-dfd#35]
@peaceiris : I realized after the fact I hadn't asked before putting you in https://github.com/danielfdickinson/build-audit-action-hugo-dfd/blob/main/docs/ACKNOWLEDGEMENTS.md .
If this is a problem I can remove that note.

**Comment by danielfdickinson** [comment]
Likewise @brycewray and @davidsneighbour. Also for other repos where I copied from https://github.com/danielfdickinson/dfd-template .

**Comment by peaceiris** [comment]
No problem. Thank you for notifying me!

**Comment by brycewray** [comment]
> Likewise @brycewray and @davidsneighbour. Also for other repos where I copied from https://github.com/danielfdickinson/dfd-template .

@danielfdickinson I appreciate the reference!
